-- +goose Up

-- +goose StatementBegin
CREATE DOMAIN uchar AS NUMERIC CHECK (VALUE >= 0::NUMERIC AND VALUE <= '255'::NUMERIC);
CREATE DOMAIN ushort AS NUMERIC CHECK (VALUE >= 0::NUMERIC AND VALUE <= '65535'::NUMERIC);
CREATE DOMAIN ulong AS NUMERIC CHECK (VALUE >= 0::NUMERIC AND VALUE <= '4294967295'::NUMERIC);
CREATE DOMAIN ulong64 AS NUMERIC CHECK (VALUE >= 0::NUMERIC AND VALUE <= '18446744073709551615'::NUMERIC);
-- +goose StatementEnd

-- +goose Down

-- +goose StatementBegin
DROP DOMAIN IF EXISTS ulong64;
DROP DOMAIN IF EXISTS ulong;
DROP DOMAIN IF EXISTS ushort;
DROP DOMAIN IF EXISTS uchar;
-- +goose StatementEnd

