version: '3.1'

networks:
  tango-api-net:

services:
  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: tango-api
      POSTGRES_USER: tango-api-user
      POSTGRES_PASSWORD: 1234
    ports:
      - "1331:5432"
    networks:
      - tango-api-net
